first_number = int(input("Please input first number "))
second_number = int(input("Please input second number "))
# big_sum = 5 - (first_number + second_number)
# print(big_sum)
print("That fact than 5 is greater then sum of your inputed numbers is: ", 5>(first_number+second_number))
print("That fact than 5 is less then sum of your inputed numbers is: ", 5<(first_number+second_number))
print("That fact than 5 is equal the sum of your inputed numbers is: ", 5==(first_number+second_number))