first_number = input("Input first number:")
second_number = input("Input second number:")
third_number = input("Input third number:")
z = (first_number == second_number)
print("The fact than your first and second numbers are equal is ",z)
z = (first_number == third_number)
print("The fact than your first and third numbers are equal is ",z)
z = (third_number == second_number)
print("The fact than your second and third numbers are equal is ",z)
z = (first_number == second_number == third_number)
print("The fact than your first,second and third numbers are equal is ",z)