name_input = input("Please enter your name: ")
print(name_input)
print(type(name_input))
surname_input = input("Please enter your surname: ")
print(surname_input)
print(type(surname_input))
age_input = input("Please enter your age: ")
age_input = int(age_input)
print(type(age_input))
degree_input = input("Please enter your degree: ")
print(degree_input)
print(type(degree_input))
work_input = input("Years of working experience: ")
work_input = float(work_input)
print(work_input)
print(type(work_input))